//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.21 at 11:27:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "some.uniqe.text", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package some.uniqe.text;
